### ISSUE TITLE
Add Backgournd Behind SVG map

### ISSUE THREAD

**Issue by vonbeardy** [vonbeardy/hd2galaxy-issues#19]
![HD2GMBG](https://github.com/vonbeardy/hd2galaxy-issues/assets/78192304/0c9af5bc-f51b-494e-9f0b-615e54f24eb9)

This is what it looks like in action on your site ❤️ (as of now).
![image](https://github.com/vonbeardy/hd2galaxy-issues/assets/78192304/7c74750e-c0c0-4353-8a45-aee1bf66ef06)

_Originally posted by @josh-allison in https://github.com/vonbeardy/hd2galaxy-issues/discussions/17_

**Comment by josh-allison** [comment]
@vonbeardy 
It would be nice if I could request to add the background (and other art assets like the planets and icons) to the project if I could create PRs on the repo; that would save you a lot of dev time.

**Comment by vonbeardy** [comment]
I appreciate the drive to help, I really do but at the moment I'm not going to be opening up my code base. Feel free to just attach what you work on to any of the issues.
