### ISSUE TITLE
Create SVG elements for all sectors

### ISSUE THREAD

**Issue by vonbeardy** [vonbeardy/hd2galaxy-issues#2]
This will replace the background image so all sectors are essentially individual programmable SVG images that can be controlled with code

**Comment by josh-allison** [comment]
@vonbeardy 
IDK if you have already made the SVGs or not. If you haven't, enjoy:

![Sectors](https://github.com/vonbeardy/hd2galaxy-issues/assets/78192304/f87818ff-49f2-42b9-b33c-ede9d3fb6899)

<details><summary>**Edit**</summary>
<p>
It looks like a single SVG, but upon inspection, you can see each path is named with the name of the associated sector.
The SVG was based on the 4k x 4k resolution of your galaxy map image.

I also have a version of this with the minimum amount of anchors, if that makes more sense to use. Let me know if there's any formatting you need done, or if you want the SVGs to be saved in a form that is editable in illustrator, etc.

Just let me know if there's anything I can do to help with the map. I have experience in Digital Art, Web Dev, and I love cartography.
</p>
</details>

**Comment by josh-allison** [comment]
Here's the updated version with only the minimum required anchors. It also has the styling started so it'll be easy for you to select by id, and add/remove classes, or edit the styling as you see fit.
![SectorsMinAnchors](https://github.com/vonbeardy/hd2galaxy-issues/assets/78192304/634e9cca-62f6-478a-acb4-213a468b39f2)

**Comment by vonbeardy** [comment]
This looks great. I have started on an SVG version that has independent SVGs so I can have full control of each sector. I'll take a look at what you have come up with here and see if this might fit some of my needs.

**Comment by vonbeardy** [comment]
@josh-allison Dude! You are a life saver and this is what I was starting to work on today. If you don't mind, do I have your permission to use this on the site?

**Comment by josh-allison** [comment]
@vonbeardy That's what it's for :)
If you need images or if I can lend a hand with programming, lmk. I have experience with both.

**Comment by vonbeardy** [comment]
@josh-allison really appreciate this! It will save me a load of time. I will work on integrating this over the next few days.

**Comment by vonbeardy** [comment]
@josh-allison, again thanks for your awesome work. This has been integrated with the site and will now show the highlighted sectors accordingly.
