### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by LacyIsntFat** [vonbeardy/hd2galaxy-issues#33]
"Angels's Venture" -> "Angel's Venture"

**Comment by vonbeardy** [comment]
🤣 whoops, I'll fix that with the next update

**Comment by vonbeardy** [comment]
Fixed and deployed

**Comment by LacyIsntFat** [comment]
idk if I should be putting spell checks and stuff on a github page lol, but "Varylia" should be "Varylia 5"
