### ISSUE TITLE
Open-source the HD2 data collection method

### ISSUE THREAD

**Issue by NeoCryptixGithub** [vonbeardy/hd2galaxy-issues#34]
It would be really interesting to be able to use it in other projects.

**Comment by ROBOT0-VT** [comment]
I'd imagine it's this:
https://github.com/helldivers-2/api

**Comment by NeoCryptixGithub** [comment]
I can't find any documentation for this

**Comment by vonbeardy** [comment]
I'm pulling directly from the game API currently with the following endpoints which the previously mentioned repo uses as well:
https://api.live.prod.thehelldiversgame.com/api/warseason/801/warinfo
https://api.live.prod.thehelldiversgame.com/api/Stats/War/801/Summary
https://api.live.prod.thehelldiversgame.com/api/v2/assignment/War/801

**Comment by NeoCryptixGithub** [comment]
Is there a faster way to contact you (@vonbeardy) for more specific questions?

**Comment by vonbeardy** [comment]
You can either use the discussion section above of github or send me an email at beardy@hd2galaxy.com
