### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toFixed')

### ISSUE THREAD

**Issue by mheptinstall** [vonbeardy/hd2galaxy-issues#38]
Site is failing to load correctly, I see the following error in the console:

> index-zCJlCkGl.js:83 
> TypeError: Cannot read properties of undefined (reading 'toFixed')
>    at PlanetDetails (index-zCJlCkGl.js:221:1903)
>    at Xh (index-zCJlCkGl.js:38:20217)
>    at Wk (index-zCJlCkGl.js:40:43780)
>    at Vk (index-zCJlCkGl.js:40:39558)
>    at Uk (index-zCJlCkGl.js:40:39489)
>    at Jk (index-zCJlCkGl.js:40:39348)
>    at Ok (index-zCJlCkGl.js:40:35741)
>    at Hk (index-zCJlCkGl.js:40:34698)
>    at at (index-zCJlCkGl.js:25:1682)
>    at MessagePort.Et (index-zCJlCkGl.js:25:2074)

**Comment by vonbeardy** [comment]
Thanks, just fixed and deployed. Should be up now
