### ISSUE TITLE
Data seems off

### ISSUE THREAD

**Issue by McGimsey** [vonbeardy/hd2galaxy-issues#48]
Bullets fired are less than bullets hit. Seems backwards at best

**Comment by vonbeardy** [comment]
I agree but the official API shows it as such which is either a bug or it is truly backwards. I don't want to assume it's backwards but rather a bug at this point. I'll keep an eye on it but unfortunately it's what the API says....
 
![image](https://github.com/vonbeardy/hd2galaxy-issues/assets/47662740/08f0d992-6ce4-4539-a086-61d489cfb2a9)

**Comment by McGimsey** [comment]
Thanks for the quick response! I'll keep an eye out

**Comment by McGimsey** [comment]
Definitely believable on the hit counter. I'd like to see the stats on
weapons used and see if shotguns could make up the difference.

**Comment by vonbeardy** [comment]
Also I had thought it could be from stratagems as well where one shot, like the 500k, could hit a lot of targets. The API isn't clear on what they are counting as a shot or a hit, just the metric.
