### ISSUE TITLE
Cyberstan and Super Earth both have Illuminate kills?

### ISSUE THREAD

**Issue by NinjaBoi273547** [vonbeardy/hd2galaxy-issues#64]
Currently, if you look at the map, Cyberstan and  Super Earth both have kills for the Illuminate documented.
![Screenshot 2024-09-26 095438](https://github.com/user-attachments/assets/077026eb-2ddb-4d24-a8ec-2d3174a45261)
![Screenshot 2024-09-26 095519](https://github.com/user-attachments/assets/5ae2cc1e-3472-4705-ad95-ad32a89eb344)

**Comment by vonbeardy** [comment]
That actually isn't a bug, in fact, that is what has been reported in the official HD2 API. Pretty interesting, right? For example, this is what the API returns for Cyberstan: 
![image](https://github.com/user-attachments/assets/2b340bdd-424f-4f3b-bef4-b71a9d226f85)
