### ISSUE TITLE
Average time estimates

### ISSUE THREAD

**Issue by FraterAdamanteus** [vonbeardy/hd2galaxy-issues#65]
Hello, your Helldivers 2 Galaxy Map is one of my most frequent visited websites for months.
But i want to make a recommendation about the estimated time calculator. You see right now the estimated time for Shelt changed from 16hours to 30 days. I guess you take the current liberation rate from an official Helldivers website and calculate the estimated time with this. I think this makes it varying so much and you should rather take the average of a longer period.

Thank you very much for your hard work, i hope the Helldivers team will also aknowlegde you and include your map somewhere in the game. It is annoying that almost 40% of all Helldivers dont think tactical if it comes to planet priorisation.

**Comment by vonbeardy** [comment]
Thanks for the positive feedback! This is something I have thought exactly the same thing with averaging. I don't retain a lot of history for metrics; only the current time and the previous time (now and -60 seconds in the past) but that should still suffice to getting the average time between those deltas.

**Comment by vonbeardy** [comment]
Added this update today. You'll hopefully see a little bit smoother time estimates based on averages of the last two estimates under the active planets section.

**Comment by FraterAdamanteus** [comment]
thank you very much <3
