### ISSUE TITLE
Defense campaing request

### ISSUE THREAD

**Issue by VicenteSebastianAlvarezOlvera** [vonbeardy/hd2galaxy-issues#66]
Hi. I'm currently working on a Helldivers 2 dashboard myself as a personal project. I've searched online but I didn't find a way to calculate the defense campaing progress, and was wondering if you could help me with that. 
Currently I understand how to calculate the enemy percentage, but not the defense progress.

I'm posting here as I'm not sure how else I could contact you.

Thanks in advance

**Comment by vonbeardy** [comment]
Reach out to me at beardy [at] hd2galaxy.com and we can chat a little bit that.
