### ISSUE TITLE
Patch notes cut off (Chrome)

### ISSUE THREAD

**Issue by jwrdpsgithub** [vonbeardy/hd2galaxy-issues#69]
When I open the patch notes, half of the display is off to the right side of the screen.

**Comment by vonbeardy** [comment]
I have a fix for this, it will be fixed this evening

**Comment by jwrdpsgithub** [comment]
I would like to note that it happens with the "About" section also

**Comment by vonbeardy** [comment]
Fixed both about and patch notes have been deployed. Thanks for pointing that out!
