### ISSUE TITLE
Mark Major Order on Map

### ISSUE THREAD

**Issue by vonbeardy** [vonbeardy/hd2galaxy-issues#8]

**Comment by josh-allison** [comment]
This icon appears in sector view at the map table. It appears above sectors currently targeted with a 'Liberation' major order.

(I can also split this into two other relevant icons: The circle and crosshair appears above planets undergoing a liberation campaign when in planetary view, and the bottom decoration appears below planets that are at 100% liberation in planetary view.)

![LiberationCampaign_SectorIcon](https://github.com/vonbeardy/hd2galaxy-issues/assets/78192304/cebe0fe6-01e6-45b5-9761-5d573271a9e9)

**Comment by vonbeardy** [comment]
Pushed update today that includes this in the major order panel and under the planet on the map (with center removed). Thanks again for the image @josh-allison !
